#DNAscan2 config.yaml with default values
#remember to populate all options that require boolean input

#DNAscan2 command line
SAMPLE_NAMES: ["", ""]
INPUT_FORMAT: fastq
INPUT_FILE_DIR:
REFERENCE_VERSION: hg19
READ_TYPE:  paired
ADDITIONAL_VCF_FILE_DIR:
OUT_DIR: output/
FILTER_VARIANTS: true
VARIANT_FILTER_STRING: FORMAT/FT == "PASS"
DEBUG: false
EXOME: false
BED: false
ADD_READ_GROUP: false
REMOVE_DUPLICATES: true
USE_OWN_TEMP_DIR: false
NUMBER_CPU: 4
MEM_GB: 16

#DNAscan2 options 
ALIGNMENT:
SNP_INDEL:
STRUCTURAL_VARIANT:
EXPANSION:
SHORT_TANDEM_REPEAT:
genotype_SHORT_TANDEM_REPEAT:
MOBILE_ELEMENT_INSERTION:
ANNOTATION:
ALSGENESCANNER:
VIRUS:
BACTERIA:
CUSTOM_MICROBES:
SEQUENCING_REPORT:
ALIGNMENT_REPORT:
SNP_INDEL_CALLS_REPORT:
ANNOTATION_RESULTS_REPORT:

#if ADD_READ_GROUP is true, add the following five fields of information
ID:
LIBRARY:
PLATFORM:
PLATFORM_UNIT:
SAMPLE:

#DNAscan2 input file paths - directories have to end in "/"
REFERENCE_FILE:
HISAT2_INDEX:
BWA_INDEX:
VIRUS_INDEX:
BACTERIA_INDEX:
CUSTOM_MICROBES_INDEX:
BED_FILE: 
GENE_LIST: 
STRELKA_DIR:
MANTA_DIR:
MELT_DIR:
ANNOVAR_DIR:
ANNOVAR_DB:
ANNOTSV_DIR:
KNOTANNOTSV_DIR:
EXPANSIONHUNTERDENOVO_DIR:
TEMPORARY_DIR:

#other configs
ANNOVAR_PROTOCOLS: refGene,dbnsfp33a,clinvar_20210501,intervar_20180118,avsnp147,exac03,ALL.sites.2015_08,gnomad211_genome
ANNOVAR_OPERATIONS: g,f,f,f,f,f,f,f
HISAT_CUSTOM_OPTIONS: None
BWA_CUSTOM_OPTIONS: None
MELT_CUSTOM_OPTIONS: None
ANNOTSV_CUSTOM_OPTIONS: None
