#DNAscan2 config.yaml with defaults

#DNAscan2 command line
SAMPLE_NAMES: ["", ""]
INPUT_FORMAT: fastq,bam,cram,vcf
INPUT_FILE_DIR:
REFERENCE_VERSION: hg19,hg38,grch37,grch38
READ_TYPE:  paired,single
ADDITIONAL_VCF_FILE_DIR:
OUT_DIR: output/
FILTER_VARIANTS:
VARIANT_FILTER_STRING:
DEBUG:
EXOME:
BED:
ADD_READ_GROUP:
REMOVE_DUPLICATES:
USE_OWN_TEMP_DIR:
NUMBER_CPU:
MEM_GB:

#DNAscan2 options (boolean)
ALIGNMENT:
SNP_INDEL:
STRUCTURAL_VARIANT:
EXPANSION:
SHORT_TANDEM_REPEAT:
genotype_SHORT_TANDEM_REPEAT:
MOBILE_ELEMENT_INSERTION:
ANNOTATION:
ALSGENESCANNER:
VIRUS:
BACTERIA:
CUSTOM_MICROBES:
SEQUENCING_REPORT:
ALIGNMENT_REPORT:
SNP_INDEL_CALLS_REPORT:
ANNOTATION_RESULTS_REPORT:

#if add read group is true, add the following five fields of information
ID:
LIBRARY:
PLATFORM:
PLATFORM_UNIT:
SAMPLE:

#DNAscan2 input file paths
REFERENCE_FILE:
HISAT2_INDEX:
BWA_INDEX:
VIRUS_INDEX:
BACTERIA_INDEX:
CUSTOM_MICROBES_INDEX:
BED_FILE:
GENE_LIST:
STRELKA_DIR:
MANTA_DIR:
MELT_DIR:
ANNOVAR_DIR:
ANNOVAR_DB:
ANNOTSV_DIR:
KNOTANNOTSV_DIR:
EXPANSIONHUNTERDENOVO_DIR:
TEMPORARY_DIR:

#other configs
ANNOVAR_PROTOCOLS:
ANNOVAR_OPERATIONS:
HISAT_CUSTOM_OPTIONS:
BWA_CUSTOM_OPTIONS:
MELT_CUSTOM_OPTIONS:
ANNOTSV_CUSTOM_OPTIONS:
